### ISSUE TITLE
jmx_prometheus_javaagent.jar file broken or corrupted

### ISSUE THREAD

**Issue by rgutierrez2004** [ptmp13/weblogic-jmx-exporter#1]
After downloading the jmx_prometheus_javaagent.jar file I can't use it, seems to be incomplete/broken or corruupted.

Wondering if we can use the JAR file from https://github.com/prometheus/jmx_exporter, or this one has specific code for Weblogic

**Comment by rgutierrez2004** [comment]
After trying different options, found a way to download the complete JAR file but then realized not all metrcis are being exposed, as no data is displayed in some panels. My WLS domain is 12.2.1.4.

**Comment by ptmp13** [comment]
Hello. What panel does`t display data?
