### ISSUE TITLE
Weblogic - dynamic cluster

### ISSUE THREAD

**Issue by farrukh1991** [ptmp13/weblogic-jmx-exporter#3]
Hi,

I have an issue during starting the managed servers. Admin server port 18001 is up and it is fine.
During starting the managed servers i m getting the following error:

Starting WLS with line:
/usr/jdk/jdk1.8.0_77/bin/java -server -d64   -Xms1536m -Xmx4096m -Dorg.apache.xml.dtm.DTMManager=org.apache.xml.dtm.ref.DTMManagerDefault -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XML11Configuration -Dweblogic.threadpool.MinPoolSize=100 -Dweblogic.threadpool.MaxPoolSize=100 -Djava.awt.headless=true -XX:MaxPermSize=512m -XX:+UseParallelOldGC -XX:ParallelGCThreads=4 -Dweblogic.Name=FCUBSProduction-2 -Djava.security.policy=/export/home/oracle/Oracle/Middleware/Oracle_Home/wlserver/server/lib/weblogic.policy -Dweblogic.system.BootIdentityFile=/export/home/oracle/Oracle/Middleware/Oracle_Home/user_projects/domains/orienubs_domain/servers/FCUBSProduction-2/data/nodemanager/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true  -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:./app/jmx_prometheus_javaagent.jar=1:./config/jmxexporter.yml  -javaagent:/export/home/oracle/Oracle/Middleware/Oracle_Home/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/export/home/oracle/Oracle/Middleware/Oracle_Home/wlserver/server -Dweblogic.home=/export/home/oracle/Oracle/Middleware/Oracle_Home/wlserver/server   -Dweblogic.management.server=http://172.16.51.17:8001  -Dweblogic.management.username=weblogic -Dweblogic.management.password=orien001  weblogic.Server
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)
	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:31)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by ptmp13** [comment]
Oh... its becouse 
-javaagent:./app/jmx_prometheus_javaagent.jar=**1**:./config/jmxexporter.yml
My script parse **config.xml** for get current managed server port. I think dynamic cluster dont write anything to config.xml so... i can rewrtie script but it takes time.

**Comment by fmamadziyoev** [comment]
Hi,
If you will rewrite, it will be wonderful.

**Comment by ptmp13** [comment]
Hi. I update scripts for support dynamic clusters. So... you can update files for your domain.
Let me know result.

**Comment by farrukh1991** [comment]
Hi,
After starting the managed servers, I still don't see any additional ports for fetching the metrics. Where did I make a mistake?

**Comment by farrukh1991** [comment]
The new files with fix already uploaded and restarted the servers.

**Comment by ptmp13** [comment]
Can you attach .out log of your managed server?

**Comment by farrukh1991** [comment]
Ohh i forgotted to change the user and pass in setUserOverrides.sh. Now i set them, but the following error during starting AdminServer and admin server is not coming up.

<Jan 22, 2024 10:31:41 AM TJT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.77-b03 from Oracle Corporation.>
<Jan 22, 2024 10:31:41 AM TJT> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>
<Jan 22, 2024 10:31:43 AM TJT> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 1 of 3).>
<Jan 22, 2024 10:31:48 AM TJT> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 2 of 3).>
<Jan 22, 2024 10:31:53 AM TJT> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 3 of 3).>
<Jan 22, 2024 10:31:58 AM TJT> <Info> <Management> <BEA-141298> <Could not register with the Administration Server: weblogic.deploy.service.internal.transport.UnreachableHostException: [Deployer:149145]Unable to contact "null". Deployment is deferred until "null" becomes available.; nested exception is:
        java.net.ConnectException: Tried all: '1' addresses, but could not connect over HTTP to server: '10.10.10.20', port: '8001'
 failed reasons:
  [0] address:'/172.16.51.29',port:'8001' : java.net.ConnectException: Connection refused

**Comment by farrukh1991** [comment]
Hi,
It is fine now, had some mistakes. Thank you very much. Let me to test the dashboard.

**Comment by farrukh1991** [comment]
In dashboard one of the managed server status is showing 17, but from console its status is FAILED. Why not showing FAILED in dashboard of grafana?

**Comment by ptmp13** [comment]
Ok i add more values but in this table
[table](https://stackoverflow.com/questions/43920529/managed-server-state-integer-value-reference)
17 is ADMIN.

**Comment by farrukh1991** [comment]
And also when the server is in SHUTDOWN mode, the port is also not listening and in Grafana it shows NO DATA....

**Comment by farrukh1991** [comment]
Can you please add all status in Dashboard?

**Comment by farrukh1991** [comment]
In one of the servers i m getting the following error. If remove setUserOverrides.sh, its ok. What to do?

./setUserOverrides.sh
./setUserOverrides.sh: line 3: $'\r': command not found
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
./setUserOverrides.sh: line 7: $'\r': command not found
! port:  no jqq in /usr/bin /usr/sbin
! port:  /usr/bin/python
./setUserOverrides.sh: line 10: $'\r': command not found
./setUserOverrides.sh: line 11: syntax error near unexpected token `$'\r''
'/setUserOverrides.sh: line 11: `getPortFromRest()

**Comment by farrukh1991** [comment]
Resolved: 

tr -d '\r' < setUserOverrides.sh > setUserOverrides_unix.sh
mv setUserOverrides_unix.sh setUserOverrides.sh

**Comment by farrukh1991** [comment]
Hi. In case of weblogic cluster, if there are 6 servers and 3 of them are in the second node, how it should fetch the ports? For me it didnt worked.

**Comment by Mr-TalhaRehman** [comment]
Hi Farrukh, are you able to get the information for the following highlighted?
![image](https://github.com/ptmp13/weblogic-jmx-exporter/assets/142668702/a3fcf2a5-2ec2-4a6f-8801-9330c89709d3)

**Comment by Mr-TalhaRehman** [comment]
![image](https://github.com/ptmp13/weblogic-jmx-exporter/assets/142668702/adc69dce-8921-46aa-b8f0-cdec865c400a)

**Comment by ptmp13** [comment]
Check read me. ensure you can get metrics from jmxport

> As Result jmx port will be 1{$MANAGEDSERVER_PORT} for example if MANAGED SERVER runnning on port 8004 jmxport will be 18004

**Comment by Mr-TalhaRehman** [comment]
I'm able to get the metrics from jmxport successfully.. but only above highlighted data is not showing up..

**Comment by ptmp13** [comment]
Hi. I add sample for prometheus service discovery file: prometheus_wls_sd.yml
Check it. Labels like weblogic_domainUID etc.. add in this file.
