### ISSUE TITLE
Various panels are not working

### ISSUE THREAD

**Issue by Nirzak** [ptmp13/weblogic-jmx-exporter#4]
Hi. Many panels are not working because the exposed metrics are not as the way in which the dashboard is using them. 

For example: if we use the jmxexporter.yml that you have mentioned in this repo then the exposed metrics are like below:

`weblogic_server_activation_time{instance="instance", job="job", name="name"}`

`weblogic_application_internal{instance="instance", job="job", name="name", runtime="serverruntime"}`

so there are only instance, runtime, name like labels. No domainUID, clusterName, serverName labels that you have used in the dashboard. The configuration is also saying so. there are no labels like domainUID, clusterName and serverName is mentioned on the jmxexporter.yml file. 

As a result, many panels are not working properly. Can you please kindly check if the mentioned jmxexporter.yml file is the one that you are using.

Thanks

**Comment by Nirzak** [comment]
Hi @ptmp13 please check this one whenever you get some free time! Thanks

**Comment by ptmp13** [comment]
Hi. I add sample for prometheus service discovery file: **prometheus_wls_sd.yml**
Check it. Labels like weblogic_domainUID etc.. add in this file.

**Comment by Nirzak** [comment]
> Hi. I add sample for prometheus service discovery file: **prometheus_wls_sd.yml** Check it. Labels like weblogic_domainUID etc.. add in this file.

Yeah I also thought so. So was trying to grab the domain name and server name from JMX mbean com.bea:Name=*, Type=Domain
but later have seen that we still need to concat all the metrics with the domain name metrics to make it work! which could be inefficient and time consuming. So have added static server name and domain name labels from the prometheus config!

**Comment by ptmp13** [comment]
I dont understand it works if you add labels like weblogic_domainUID to service discovery file?

**Comment by Nirzak** [comment]
> I dont understand it works if you add labels like weblogic_domainUID to service discovery file?

Yeah this is one approach. I mean the approach you have mentioned. We can define weblogic_domainUID label from prometheus.yml config. but there's a drawback of this approach. and that is support we have 10 and each domain have 6 managed servers. so we have to add weblogic_domainUID and server name for all those 60 entities! which is actually inefficient for bigger scenarios. something like if we can dynamically attach it to the metrics from JMX mbeans that would be better. but JMX mbean only give separate mbean for domain name and servername related information that's the problem.

**Comment by ptmp13** [comment]
yes i understand, but now its only way to achive this. I have no time for rewrite jmxexporter for weblogic. You can try official metric exporter https://github.com/oracle/weblogic-monitoring-exporter, but last time when i use it there was too few metrics...

**Comment by Nirzak** [comment]
> yes i understand, but now its only way to achive this. I have no time for rewrite jmxexporter for weblogic. You can try official metric exporter https://github.com/oracle/weblogic-monitoring-exporter, but last time when i use it there was too few metrics...

I had already rewritten a JMX exporter config. but that can't be completely achieved with JMX exporter config as I have stated earlier. Yes WebLogic monitoring exporter has all kinds of WebLogic config now. but that lacks some JVM metrics. However thanks a lot man. I am going to close issue now.
